import Diaspora.Logic.Basic
import Diaspora.Core.Weighted
import Diaspora.Dynamics.Transition
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.FieldSimp
import Mathlib.Data.Real.Basic

open BigOperators Diaspora.Core Diaspora.Hodge Diaspora.Dynamics Diaspora.Logic

namespace Diaspora.Models

/-! ## 1. The Bundle Topology -/

/--
System: Source (0), Sink (1), and 3 Witnesses (2, 3, 4).
Total nodes = 5.
-/
abbrev n_bundle : ℕ := 5
@[simp] lemma fin_b0 : (0 : Fin n_bundle) = ⟨0, by decide⟩ := rfl
@[simp] lemma fin_b1 : (1 : Fin n_bundle) = ⟨1, by decide⟩ := rfl
@[simp] lemma fin_b2 : (2 : Fin n_bundle) = ⟨2, by decide⟩ := rfl
@[simp] lemma fin_b3 : (3 : Fin n_bundle) = ⟨3, by decide⟩ := rfl
@[simp] lemma fin_b4 : (4 : Fin n_bundle) = ⟨4, by decide⟩ := rfl

/--
The Theory: a contradiction between one heavy constraint and many light ones.
- Heavy edge: (0→1) demands flux 10.
- Light paths: (0→2→1), (0→3→1), (0→4→1) demand flux 0.
-/
def bundle_theory : Theory n_bundle := [
  ⟨0, 1, 10⟩,    -- Heavy edge
  ⟨0, 2, 0⟩, ⟨2, 1, 0⟩, -- Light path 1
  ⟨0, 3, 0⟩, ⟨3, 1, 0⟩, -- Light path 2
  ⟨0, 4, 0⟩, ⟨4, 1, 0⟩  -- Light path 3
]

/-- The graph implied by the theory. -/
def bundle_graph : DynamicGraph n_bundle := theory_graph bundle_theory

/-! ## 2. Asymmetric Weights -/

/--
Raw (unnormalized) weights where the heavy edge dominates.
Heavy edge weight = 100, Light edge weight = 1.
-/
def raw_weights : Fin n_bundle → Fin n_bundle → ℝ := fun i j =>
  if (i=0 ∧ j=1) ∨ (i=1 ∧ j=0) then 100
  else if (i, j) ∈ bundle_graph.active_edges then 1
  else 0

/-- The sum of raw weights: 2×100 (heavy edges) + 12×1 (light edges) = 212 -/
lemma raw_weights_sum : ∑ i, ∑ j, raw_weights i j = 212 := by
  unfold raw_weights
  simp only [Fin.sum_univ_five]; simp (config := { decide := true }); norm_num

/--
Normalized weights that sum to n². Preserves the 100:1 ratio.
-/
noncomputable def asymmetric_weights : WeightedGraph n_bundle where
  weights := fun i j => raw_weights i j * (25 / 212)
  symmetric := by
    intro i j
    unfold raw_weights
    fin_cases i <;> fin_cases j <;> simp [bundle_graph] <;> rfl
  nonneg := by
    intro i j
    apply mul_nonneg
    · unfold raw_weights; split_ifs <;> norm_num
    · norm_num
  total_capacity_fixed := by
    simp only [← Finset.sum_mul, raw_weights_sum]
    norm_num

/-! ## 3. Strain Localization -/

/-- The total weighted energy for a given potential ϕ. -/
noncomputable def weighted_energy (G : WeightedGraph n_bundle) (ϕ : C0 n_bundle) (σ : C1 n_bundle) : ℝ :=
  (1/2) * ∑ i, ∑ j, G.weights i j * ((d0 ϕ).val i j - σ.val i j)^2

/--
Analytical solution for the optimal potential.
Since the heavy edge is 100x heavier, the solver mostly satisfies it (ϕ1 - ϕ0 = 10).
Witnesses sit at the midpoint, bearing the strain.
-/
noncomputable def lazy_phi : C0 n_bundle := fun i =>
  match i with
  | 0 => 0
  | 1 => 10
  | 2 => 5  -- Witnesses sit halfway
  | 3 => 5
  | 4 => 5

/--
The representational demand σ generated by the theory.
-/
noncomputable def σ_bundle : C1 n_bundle := (realize bundle_theory).val

/-! ## 4. The Shape of Contradiction -/

/--
The heavy edge is satisfied: strain = 0.
Weighted optimization found a potential that perfectly relaxes the dominant constraint.
-/
theorem heavy_edge_relaxed (i j : Fin n_bundle) (h : i=0 ∧ j=1) :
    edge_strain lazy_phi σ_bundle i j = 0 := by
  unfold edge_strain
  rcases h with ⟨rfl, rfl⟩
  simp [d0, lazy_phi, σ_bundle, realize, raw_flux, find_constraint, bundle_theory]

/--
The light edges bear all the strain.
Flux demanded is 0, but the potential forced by the heavy edge creates differences of 5.
Strain = (5 - 0)² = 25.
-/
theorem light_edges_strained :
    edge_strain lazy_phi σ_bundle 0 2 = 25 ∧
    edge_strain lazy_phi σ_bundle 2 1 = 25 := by
  constructor <;>
  (unfold edge_strain
   simp [d0, lazy_phi, σ_bundle, realize, raw_flux, find_constraint, bundle_theory]
   norm_num)

/--
Main Result: Weight determines breaking order.
If the breaking threshold C_max is 20, the light edges break first,
even though they constitute the majority of constraints (6 vs 1).
-/
theorem weight_determines_breaking (C_max : ℝ) (h_threshold : C_max = 20) :
    -- The light edge (0,2) is overstressed
    edge_strain lazy_phi σ_bundle 0 2 > C_max ∧
    -- The heavy edge (0,1) is safe
    edge_strain lazy_phi σ_bundle 0 1 < C_max := by
  rw [h_threshold]
  constructor
  · -- 25 > 20
    have h := (light_edges_strained).1
    linarith
  · -- 0 < 20
    have h := heavy_edge_relaxed 0 1 ⟨rfl, rfl⟩
    linarith

/-!
## Interpretation

Weighted optimization and constraint-counting disagree on "what should break."
The heavy edge persists (strain = 0), while light edges break (strain = 25).
This is the shape of contradiction under asymmetric attention.
-/

end Diaspora.Models
